### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by brewmanandi** [theapache64/remove-bg#1]
You have your remove.bg API key committed in the repo. You should get a new one and remove it from the repo.

**Comment by theapache64** [comment]
I put the API key purposefully in the demo app because I don't use that account for any other purposes except for the demo, plus the usage limit is very minimal.So I think external usage is not a problem. Also, it'll be good if the demo works without changing any params.

Now, When it comes to usage expiry, the demo fails with expiry notice. Hence, I think it's much better to update the API key with some good instruction. So the demo fails with the instruction rather than expiry notice. 

Thanks for reporting this issue.
